export const ACTIVITY_TYPES = Object.freeze({
  EVENT_VIEWED: "EVENT_VIEWED",
  BOOKING_STARTED: "BOOKING_STARTED",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
});
