export const RESPONSE_CODES = Object.freeze({
    SERVER_HEALTHY: "SERVER_HEALTHY",

    // Authentication
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",

    // Event
    EVENT_CREATED: "EVENT_CREATED",

    // Booking
    BOOKING_CREATED: "BOOKING_CREATED",
    BOOKING_CANCELLED: "BOOKING_CANCELLED",
});