export const RESPONSE_CODES = Object.freeze({
  // HEALTH
  SERVER_HEALTHY: "SERVER_HEALTHY",

  // AUTH
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  // EVENT
  EVENT_CREATED: "EVENT_CREATED",
  EVENT_UPDATED: "EVENT_UPDATED",
  EVENTS_FETCHED: "EVENTS_FETCHED",
  EVENT_NOT_FOUND: "EVENT_NOT_FOUND",
  CAPACITY_LESS_THAN_BOOKED_SEATS: "CAPACITY_LESS_THAN_BOOKED_SEATS",

  // BOOKING
  BOOKING_CREATED: "BOOKING_CREATED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
});
